### ISSUE TITLE
php: error while loading shared libraries: libtinfo.so.6

### ISSUE THREAD

**Issue by ebauger** [juicyfx/now-php#42]
Really nice project!

I will try to deploy with now my slim api projet.

now.json
```
{
    "functions": {
      "public/*.php": {
        "runtime": "now-php@0.0.8"
      }
    }
  }
```

composer.json
```
{
    "require": {
        "php": "^7.3",
        "slim/slim": "^4.3",
        "slim/psr7": "^0.6.0",
        "vlucas/phpdotenv": "^4.0"
    }
}
```

I got this error log on my now instance :
```
05:34:54 PM | Downloading 234 deployment files...
-- | --
05:35:07 PM | Installing build runtime...
05:35:10 PM | Build runtime installed: 2752.461ms
05:35:11 PM | Looking up build cache...
05:35:12 PM | 🐘 Installing Composer deps.
05:35:12 PM | php: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
05:35:12 PM | Error: Exited with 127
05:35:12 PM | at ChildProcess.child.on (/zeit/fa5b89e012ce722c/.build-utils/.builder/node_modules/now-php/dist/utils.js:151:24)
05:35:12 PM | at emitTwo (events.js:126:13)
05:35:12 PM | at ChildProcess.emit (events.js:214:7)
05:35:12 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
05:35:12 PM | worker exited with code 1 and signal null
05:35:12 PM | done
05:35:13 PM | Installing build runtime...
05:35:14 PM | Build runtime installed: 491.000ms
05:35:14 PM | Looking up build cache...
05:35:16 PM | 🐘 Installing Composer deps.
05:35:16 PM | php: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
05:35:16 PM | Error: Exited with 127
05:35:16 PM | at ChildProcess.child.on (/zeit/fa5b89e012ce722c/.build-utils/.builder/node_modules/now-php/dist/utils.js:151:24)
05:35:16 PM | at emitTwo (events.js:126:13)
05:35:16 PM | at ChildProcess.emit (events.js:214:7)
05:35:16 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
05:35:16 PM | worker exited with code 1 and signal null
05:35:16 PM | done
05:35:16 PM | Installing build runtime...
05:35:17 PM | Build runtime installed: 518.264ms
05:35:17 PM | Looking up build cache...
05:35:19 PM | 🐘 Installing Composer deps.
05:35:19 PM | php: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
05:35:19 PM | Error: Exited with 127
05:35:19 PM | at ChildProcess.child.on (/zeit/fa5b89e012ce722c/.build-utils/.builder/node_modules/now-php/dist/utils.js:151:24)
05:35:19 PM | at emitTwo (events.js:126:13)
05:35:19 PM | at ChildProcess.emit (events.js:214:7)
05:35:19 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
05:35:19 PM | worker exited with code 1 and signal null
05:35:19 PM | done
05:35:20 PM | Installing build runtime...
05:35:20 PM | Build runtime installed: 408.707ms
05:35:21 PM | Looking up build cache...
05:35:22 PM | 🐘 Installing Composer deps.
05:35:23 PM | php: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
05:35:23 PM | Error: Exited with 127
05:35:23 PM | at ChildProcess.child.on (/zeit/fa5b89e012ce722c/.build-utils/.builder/node_modules/now-php/dist/utils.js:151:24)
05:35:23 PM | at emitTwo (events.js:126:13)
05:35:23 PM | at ChildProcess.emit (events.js:214:7)
05:35:23 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
05:35:23 PM | worker exited with code 1 and signal null
05:35:23 PM | done
05:35:23 PM | Installing build runtime...
05:35:23 PM | Build runtime installed: 415.674ms
05:35:24 PM | Looking up build cache...
05:35:26 PM | 🐘 Installing Composer deps.
05:35:26 PM | php: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
05:35:26 PM | Error: Exited with 127
05:35:26 PM | at ChildProcess.child.on (/zeit/fa5b89e012ce722c/.build-utils/.builder/node_modules/now-php/dist/utils.js:151:24)
05:35:26 PM | at emitTwo (events.js:126:13)
05:35:26 PM | at ChildProcess.emit (events.js:214:7)
05:35:26 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
05:35:26 PM | worker exited with code 1 and signal null
05:35:28 PM | done
```

Any tips?

**Comment by ebauger** [comment]
Also try with this new version of now.json but I had the same issue:
```
{
    "functions": {
      "public/*.php": {
        "runtime": "now-php@0.0.8"
      }
    },
    "routes": [
      {"src": ".*", "dest": "/public/index.php"}
    ],
    "build": {
      "env": {
        "NOW_PHP_DEBUG" : "1"
      }
    }
  }
```

**Comment by f3l1x** [comment]
Hi @ebauger. It's strange. Thank you for reporting. I must take a look closer.

**Comment by ebauger** [comment]
@f3l1x If you need more info you can poke me anytimes

**Comment by f3l1x** [comment]
I've discuss it with @styfle and problem is in building phase. 

Build container during building phase use AL1 (`amazonlinux:2017.03.1.20170812`). That's the problem. PHP 7.4 is compiled for runtime container running on Amazon Linux 2.

Only installing Composer dependencies is affected. Not the runtime (I think). Using prepacked Composer dependencies might work for now.

First things came to my ming are:
 
- used prepacked dependencies (for now) and put composer.json in `.nowignore` file
- use PHP 7.3 for installing composer dependencies
- somehow compile PHP 7.4 for AL1 and use it in build phase
- build special lambda for installing Composer dependencies, take composer.json|lock, send them there and download dependencies (vendor)

------

Any other thoughts?

------

More sources:

- https://zeit.co/juicyfx/now-php-composer/2foyvvfki
- https://zeit.co/juicyfx/now-php-composer/o98ojjitq
- https://zeit.co/juicyfx/now-php-composer/pnjb67gbi
- https://zeit.co/juicyfx/now-php-composer/ega7dw979
- https://forums.aws.amazon.com/thread.jspa?threadID=296602&tstart=0

**Comment by kolyasapphire** [comment]
Hi! I can confirm this affects only builds with Composer - all my projects without it redeployed and are working fine after the 0.0.8 update.

Would it be possible to install Composer packages using PHP 7.3, but use 7.4 to build the lambdas?

**Comment by ebauger** [comment]
@f3l1x I will try your output and give feedback

**Comment by AGDholo** [comment]
Same thing when I use the latest lumen app

**Comment by f3l1x** [comment]
Could you guys @AGDholo @ebauger @kolyasapphire test this setup?

```
  "functions": {
    "api/index.php": {
      "runtime": "now-php@0.0.9-experimental.1"
    }
  }
```

**Comment by ebauger** [comment]
@f3l1x 

```
.
├── LICENSE
├── README.md
├── api
│   ├── WSClass.php
│   ├── index.php
├── composer.json
├── composer.lock
└── now.json
```
I had to rename my folder /public to /api in my project.

.nowignore with this line `composer.json`
 
now.json

```
{
  "functions": {
    "api/index.php": {
      "runtime": "now-php@0.0.9-experimental.1"
    }
  }
}

```
When I try a GET route on my api like https://url.now.sh/user :
```
404: NOT_FOUND
Code: RESOURCE_NOT_FOUND
ID: `cle1:q6m6g-1579122366269-xxxxxxxxxxxx`
```

any other configuration in now.json?

**Comment by kolyasapphire** [comment]
@f3l1x Thank you very much! Works as expected now.

**Comment by AGDholo** [comment]
@f3l1x 
Work nicely when I change the runtime in lumen framework:
https://github.com/OpenEpicData/NowLumenCore/blob/master/now.json

```
  "builds": [
    {
      "src": "public/index.php",
      "use": "now-php@0.0.9-experimental.1",
      "config": {
        "mode": "cgi",
        "composer": true
      }
    }
  ],
```

Might we need to fix this repo example code:
https://github.com/juicyfx/now-php/tree/master/examples/framework-lumen

**Comment by f3l1x** [comment]
Hey folks! 🎉 

New stable version bumped!

```json
{
  "functions": {
    "api/*.php": {
      "runtime": "now-php@0.0.9"
    }
  },
  "routes": [
    { "src": "/(.*)", "dest": "/api/$1" }
  ]
}
```

Related info:

- v0.0.9 #45 
- [Changelog](https://github.com/juicyfx/now-php/blob/57f3efa54824468a1c08ca5d69f748ca396b42ec/CHANGELOG.md)
